id: P000292
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W740
  title: འདུལ་བའི་གླེང་འབུམ་ཆེན་མོ།
  author: ''
  volumes:
    373d5307d03c42e0bdeb8002996f149e:
      image_group_id: I2DB57600
      title: Volume 1 of 'dul ba'i gleng 'bum chen mo
      volume_number: 1
      total_pages: 1112
      base_file: v001.txt
