id: I1EEDE9FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T15:50:01+00:00'
last_modified: '2022-06-09T17:50:21.256544+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W740
  title: འདུལ་བའི་གླེང་འབུམ་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3DDD:
      image_group_id: I2DB57600
      title: Volume 1 of 'dul ba'i gleng 'bum chen mo
      total_pages: 1112
      order: 1
      base_file: 3DDD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
